vim.g.nvim_tree_width = 40
vim.g.nvim_tree_side = "left"
vim.g.nvim_open_on_directory = 1
vim.g.nvim_tree_disable_netrw = 0
vim.g.nvim_tree_hijack_netrw = 1
vim.g.nvim_tree_auto_open = 1
-- vim.g.nvim_tree_add_trailing = 1
-- vim.g.nvim_tree_allow_resize = 1
-- vim.g.nvim_tree_auto_ignore_ft = { "dashboard" }
-- vim.g.nvim_tree_auto_open = 1
-- vim.g.nvim_tree_follow = 1
-- vim.g.nvim_tree_git_hl = 1
-- vim.g.nvim_tree_gitignore = 1
-- vim.g.nvim_tree_hide_dotfiles = 0
-- vim.g.nvim_tree_highlight_opened_files = 0
-- vim.g.nvim_tree_ignore = { ".git", "node_modules", ".cache" }
-- vim.g.nvim_tree_indent_markers = 0
-- vim.g.nvim_tree_lsp_diagnostics = 0
-- vim.g.nvim_tree_respect_buf_cwd = 1
-- vim.g.nvim_tree_root_folder_modifier = table.concat { ":t:gs?$?/..", string.rep(" ", 1000), "?:gs?^??" }
-- vim.g.nvim_tree_side = "left"
-- vim.g.nvim_tree_update_cwd = 1
