return {

  { "windwp/nvim-spectre", enabled = false },
  -- { "lewis6991/gitsigns.nvim", enabled = false },
  -- { "hrsh7th/nvim-cmp", enabled = false },
  -- { "hrsh7th/cmp-nvim-lsp", enabled = false },
  -- { "akinsho/bufferline.nvim", enabled = false },
  -- { "nvim-lualine/lualine.nvim", enabled = false },
  -- { "folke/noice.nvim", enabled = false },
  -- { "echasnovski/mini.icons", enabled = false },
  -- { "nvimdev/dashboard-nvim", enabled = false },
  -- { "rcarriga/nvim-notify", enabled = false },
  -- { "neovim/nvim-lspconfig", enabled = false },
  -- { "williamboman/mason.nvim", enabled = false },
  -- { "williamboman/mason-lspconfig.nvim", enabled = false },
  -- { "echasnovski/mini.pairs", enabled = false },
  -- { "echasnovski/mini.ai", enabled = false },
  -- { "folke/flash.nvim", enabled = false },
  -- { "folke/which-key.nvim", enabled = false },
  -- { "folke/todo-comments.nvim", enabled = false },
  -- { "mfussenegger/nvim-lint", enabled = false },
  -- { "nvim-treesitter/nvim-treesitter", enabled = false },
  -- { "nvim-treesitter/nvim-treesitter-textobjects", enabled = false },
  -- { "windwp/nvim-ts-autotag", enabled = false },
  -- { "folke/ts-comments.nvim", enabled = false },
  -- { "folke/persistence.nvim", enabled = false },
  -- { "indent-blankline.nvim", enabled = false },
}
